/* eslint-disable @typescript-eslint/no-explicit-any */
// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.




export const OWNER: string = 'Owner';
export const PHARMACY: string = 'Pharmacy';
export const BILLING: string = 'Billing';
export const MANAGER: string = 'Retail Manager';
export const BOOKKEEPER: string = 'Bookkeeper';



