/* eslint-disable @typescript-eslint/no-explicit-any */
// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.





export interface IMultipleDictionaries {
  dictionary1?: Record<string, string>;
  dictionary2?: Record<string, string> | null;
  dictionary3?: Record<string, string | null>;
  dictionary4?: Record<string, string | null> | null;
}

export class MultipleDictionaries implements IMultipleDictionaries {
  public $type: string;
  public dictionary1: Record<string, string>;
  public dictionary2?: Record<string, string> | null;
  public dictionary3: Record<string, string | null>;
  public dictionary4?: Record<string, string | null> | null;

  constructor(initObj?: IMultipleDictionaries) {
    this.$type = 'AngularWebApiSample.Models.MultipleDictionaries,'
            + 'AngularWebApiSample';
    if (initObj) {
      this.dictionary1 = initObj.dictionary1 ?? {};
      this.dictionary2 = initObj.dictionary2 ?? null;
      this.dictionary3 = initObj.dictionary3 ?? {};
      this.dictionary4 = initObj.dictionary4 ?? null;
    } else {
      this.dictionary1 = {};
      this.dictionary2 = null;
      this.dictionary3 = {};
      this.dictionary4 = null;
    }
  }
}



