/* eslint-disable @typescript-eslint/no-explicit-any */
// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.



import { ComplexAModel } from './ComplexAModel';

export interface IMultipleLists {
  list1?: string[];
  list2?: string[] | null;
  list3?: (string | null)[];
  list4?: (string | null)[] | null;
  list5?: ComplexAModel[];
  list6?: ComplexAModel[] | null;
  list7?: (ComplexAModel | null)[];
  list8?: (ComplexAModel | null)[] | null;
  list9?: string[][];
  list10?: string[][] | null;
  list11?: (string[] | null)[];
  list12?: (string[] | null)[] | null;
}

export class MultipleLists implements IMultipleLists {
  public $type: string;
  public list1: string[];
  public list2?: string[] | null;
  public list3: (string | null)[];
  public list4?: (string | null)[] | null;
  public list5: ComplexAModel[];
  public list6?: ComplexAModel[] | null;
  public list7: (ComplexAModel | null)[];
  public list8?: (ComplexAModel | null)[] | null;
  public list9: string[][];
  public list10?: string[][] | null;
  public list11: (string[] | null)[];
  public list12?: (string[] | null)[] | null;

  constructor(initObj?: IMultipleLists) {
    this.$type = 'AngularWebApiSample.Models.MultipleLists,'
            + 'AngularWebApiSample';
    if (initObj) {
      this.list1 = initObj.list1 ?? [];
      this.list2 = initObj.list2 ?? null;
      this.list3 = initObj.list3 ?? [];
      this.list4 = initObj.list4 ?? null;
      this.list5 = initObj.list5 ?? [];
      this.list6 = initObj.list6 ?? null;
      this.list7 = initObj.list7 ?? [];
      this.list8 = initObj.list8 ?? null;
      this.list9 = initObj.list9 ?? [];
      this.list10 = initObj.list10 ?? null;
      this.list11 = initObj.list11 ?? [];
      this.list12 = initObj.list12 ?? null;
    } else {
      this.list1 = [];
      this.list2 = null;
      this.list3 = [];
      this.list4 = null;
      this.list5 = [];
      this.list6 = null;
      this.list7 = [];
      this.list8 = null;
      this.list9 = [];
      this.list10 = null;
      this.list11 = [];
      this.list12 = null;
    }
  }
}



