// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.


import { SimpleModel } from './SimpleModel';

export interface ICombinedQueryModel {
    id?: number;
    simpleModels?: SimpleModel[];
}

export class CombinedQueryModel implements ICombinedQueryModel {
    public id: number;
    public simpleModels: SimpleModel[];

    constructor(initObj?: ICombinedQueryModel) {
        this.$type = undefined;
        if (initObj) {
            this.id = initObj.id || 0;
            this.simpleModels = initObj.simpleModels || [];
        } else {
            this.id = 0;
            this.simpleModels = [];
        }
    }
}


