// This file has been AUTOGENERATED by TypeWriter (https://frhagn.github.io/Typewriter/).
// Do not modify it.


import { SimpleModel } from './SimpleModel';

export interface ICombinedQueryModel {
    $type?: string;
    id?: number;
    simpleModels?: SimpleModel[];
}

export class CombinedQueryModel implements ICombinedQueryModel {
    public $type: string;
    public id: number;
    public simpleModels: SimpleModel[];

    constructor(initObj?: ICombinedQueryModel) {
        this.$type = 'ReactWebApiSample.Models.CombinedQueryModel,'
            + 'ReactWebApiSample.Models';
        if (initObj) {
            this.id = initObj.id || 0;
            this.simpleModels = initObj.simpleModels || [];
        } else {
            this.id = 0;
            this.simpleModels = [];
        }
    }
}


