// This file has been AUTOGENERATED by TypeWriter (https://github.com/adaskothebeast/Typewriter).
// Do not modify it.


import { IComplexBaseModel, ComplexBaseModel } from './ComplexBaseModel';

export interface IComplexBModel extends IComplexBaseModel {
    isActive?: boolean;
}

export class ComplexBModel extends ComplexBaseModel implements IComplexBModel {
    public isActive: boolean;

    constructor(initObj?: IComplexBModel) {
        super(initObj);
        this.$type = 'ReactWebApiSample.Models.ComplexBModel,'
            + 'ReactWebApiSample.Models';
        if (initObj) {
            this.isActive = initObj.isActive || false;
        } else {
            this.isActive = false;
        }
    }
}


