// This file has been AUTOGENERATED by TypeWriter (https://frhagn.github.io/Typewriter/).
// Do not modify it.


import { string } from './string';
import { IComplexBaseModel, ComplexBaseModel } from './ComplexBaseModel';

export interface IComplexAModel extends IComplexBaseModel {
    text?: string[];
}

export class ComplexAModel extends ComplexBaseModel implements IComplexAModel {
    public text: string[];

    constructor(initObj?: IComplexAModel) {
        super(initObj);
        this.$type = 'AngularWebApiSample.Models.ComplexAModel,'
            + 'AngularWebApiSample.Models';
        if (initObj) {
            this.text = initObj.text || [];
        } else {
            this.text = [];
        }
    }
}
