// This file has been AUTOGENERATED by TypeWriter (https://frhagn.github.io/Typewriter/).
// Do not modify it.





export interface ISimpleModel {
    $type?: string;
    num?: number;
    text?: string | null;
    isOk?: boolean;
}

export class SimpleModel implements ISimpleModel {
    public $type: string;
    public num: number;
    public text: string | null;
    public isOk: boolean;

    constructor(initObj?: ISimpleModel) {
        this.$type = 'AngularWebApiSample.Models.SimpleModel,'
            + 'AngularWebApiSample.Models';
        if (initObj) {
            this.num = initObj.num || 0;
            this.text = initObj.text || null;
            this.isOk = initObj.isOk || false;
        } else {
            this.num = 0;
            this.text = null;
            this.isOk = false;
        }
    }
}

