// This file has been AUTOGENERATED by TypeWriter (https://frhagn.github.io/Typewriter/).
// Do not modify it.


import { string } from './string';

export interface ISimpleModel {
    $type?: string;
    num?: number;
    text?: string[];
    isOk?: boolean;
}

export class SimpleModel implements ISimpleModel {
    public $type: string;
    public num: number;
    public text: string[];
    public isOk: boolean;

    constructor(initObj?: ISimpleModel) {
        this.$type = 'AngularWebApiSample.Models.SimpleModel,'
            + 'AngularWebApiSample.Models';
        if (initObj) {
            this.num = initObj.num || 0;
            this.text = initObj.text || [];
            this.isOk = initObj.isOk || false;
        } else {
            this.num = 0;
            this.text = [];
            this.isOk = false;
        }
    }
}
